#name: Sign-offs
#
#on:
#  pull_request: {}
#
#permissions:
#  contents: read
#
#jobs:
#
#  signoffs:
#    runs-on: ubuntu-latest
#    steps:
#      - { name: Checkout, uses: actions/checkout@v4, with: { fetch-depth: 0 } }
#      - name: Check commit signatures
#        if: github.event_name == 'pull_request'
#        run: |
#          for commit in $(git rev-list "origin/${{ github.base_ref }}".."${{ github.event.pull_request.head.sha }}"); do
#            if ! git verify-commit --raw $commit 2>&1 | grep -iq SIG; then
#              echo "--------------------------------------------------------------"
#              echo "Error: Commit $commit is not signed using GPG, SSH, or S/MIME"
#              echo "https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits"
#              echo "--------------------------------------------------------------"
#              git log -1 --pretty=format:"%h %s" $commit
#              exit 1
#            fi
#          done
